### ISSUE TITLE
Add confirmation modal for Deleting projects/workspaces

### ISSUE THREAD

**Issue by alexiglesias93** [finsweet/wized-roadmap#47]
We should ask for double confirmation before deleting a project or a workspace.

**Comment by xlvisben** [comment]
@besart-finsweet this seems implemented

**Comment by alexiglesias93** [comment]
It's not, confirmation modal means that it asks for double confirmation from the user.
Right now we only display a `window.confirm()` browser modal, but that's not enough for a destructive action like deleting a project.
Users should see a modal that asks a security question like "type `NAME_OF_THE_PROJECT` in this input to confirm the project deletion".
